// export const platformNames: Record<
//   string,
//   {
//     tiktok: string;
//     instagram: string;
//     youtube: string;
//     youtubeMp3: string;
//     facebook: string;
//     twitter: string;
//   }
// > = {
//   en: {
//     tiktok: "TikTok Video Download Tool",
//     instagram: "Instagram Video Download Tool",
//     youtube: "YouTube Video Download Tool",
//     youtubeMp3: "YouTube to MP3 Converter Tool",
//     facebook: "Facebook Video Download Tool",
//     twitter: "Twitter Video Download Tool",
//   },
//   de: {
//     tiktok: "TikTok Video Downloaden Tool",
//     instagram: "Instagram Video Downloaden Tool",
//     youtube: "YouTube Video Downloaden Tool",
//     youtubeMp3: "YouTube zu MP3 Konverter",
//     facebook: "Facebook Video Downloaden Tool",
//     twitter: "Twitter Video Downloaden Tool",
//   },
//   es: {
//     tiktok: "Descargador de videos de TikTok",
//     instagram: "Descargador de videos de Instagram",
//     youtube: "Descargador de videos de YouTube",
//     youtubeMp3: "Convertidor de YouTube a MP3",
//     facebook: "Descargador de videos de Facebook",
//     twitter: "Descargador de videos de Twitter",
//   },
//   fr: {
//     tiktok: "Téléchargeur de vidéos TikTok",
//     instagram: "Téléchargeur de vidéos Instagram",
//     youtube: "Téléchargeur de vidéos YouTube",
//     youtubeMp3: "Convertisseur YouTube en MP3",
//     facebook: "Téléchargeur de vidéos Facebook",
//     twitter: "Téléchargeur de vidéos Twitter",
//   },
//   hi: {
//     tiktok: "टिकटॉक वीडियो डाउनलोड टूल",
//     instagram: "इंस्टाग्राम वीडियो डाउनलोड टूल",
//     youtube: "यूट्यूब वीडियो डाउनलोड टूल",
//     youtubeMp3: "यूट्यूब से MP3 कनवर्टर टूल",
//     facebook: "फेसबुक वीडियो डाउनलोड टूल",
//     twitter: "ट्विटर वीडियो डाउनलोड टूल",
//   },
//   id: {
//     tiktok: "Pengunduh Video TikTok",
//     instagram: "Pengunduh Video Instagram",
//     youtube: "Pengunduh Video YouTube",
//     youtubeMp3: "Konverter YouTube ke MP3",
//     facebook: "Pengunduh Video Facebook",
//     twitter: "Pengunduh Video Twitter",
//   },
//   it: {
//     tiktok: "Scarica video TikTok",
//     instagram: "Scarica video Instagram",
//     youtube: "Scarica video YouTube",
//     youtubeMp3: "Convertitore YouTube in MP3",
//     facebook: "Scarica video Facebook",
//     twitter: "Scarica video Twitter",
//   },
//   ja: {
//     tiktok: "ティックトック動画ダウンローダー",
//     instagram: "インスタグラム動画ダウンローダー",
//     youtube: "ユーチューブ動画ダウンローダー",
//     youtubeMp3: "ユーチューブMP3変換ツール",
//     facebook: "フェイスブック動画ダウンローダー",
//     twitter: "ツイッター動画ダウンローダー",
//   },
//   ko: {
//     tiktok: "틱톡 동영상 다운로드 도구",
//     instagram: "인스타그램 동영상 다운로드 도구",
//     youtube: "유튜브 동영상 다운로드 도구",
//     youtubeMp3: "유튜브 MP3 변환 도구",
//     facebook: "페이스북 동영상 다운로드 도구",
//     twitter: "트위터 동영상 다운로드 도구",
//   },
//   ms: {
//     tiktok: "Muat Turun Video TikTok",
//     instagram: "Muat Turun Video Instagram",
//     youtube: "Muat Turun Video YouTube",
//     youtubeMp3: "Penukar YouTube ke MP3",
//     facebook: "Muat Turun Video Facebook",
//     twitter: "Muat Turun Video Twitter",
//   },
//   my: {
//     tiktok: "TikTok ဗီဒီယိုဒေါင်းလုပ်ကိရိယာ",
//     instagram: "Instagram ဗီဒီယိုဒေါင်းလုပ်ကိရိယာ",
//     youtube: "YouTube ဗီဒီယိုဒေါင်းလုပ်ကိရိယာ",
//     youtubeMp3: "YouTube ကို MP3 သို့ပြောင်းသည့်ကိရိယာ",
//     facebook: "Facebook ဗီဒီယိုဒေါင်းလုပ်ကိရိယာ",
//     twitter: "Twitter ဗီဒီယိုဒေါင်းလုပ်ကိရိယာ",
//   },
//   fil: {
//     tiktok: "Downloader ng TikTok Video",
//     instagram: "Downloader ng Instagram Video",
//     youtube: "Downloader ng YouTube Video",
//     youtubeMp3: "YouTube sa MP3 Converter Tool",
//     facebook: "Downloader ng Facebook Video",
//     twitter: "Downloader ng Twitter Video",
//   },
//   pt: {
//     tiktok: "Baixador de vídeos TikTok",
//     instagram: "Baixador de vídeos Instagram",
//     youtube: "Baixador de vídeos YouTube",
//     youtubeMp3: "Conversor de YouTube para MP3",
//     facebook: "Baixador de vídeos Facebook",
//     twitter: "Baixador de vídeos Twitter",
//   },
//   ru: {
//     tiktok: "Загрузчик видео TikTok",
//     instagram: "Загрузчик видео Instagram",
//     youtube: "Загрузчик видео YouTube",
//     youtubeMp3: "Конвертер YouTube в MP3",
//     facebook: "Загрузчик видео Facebook",
//     twitter: "Загрузчик видео Twitter",
//   },
//   th: {
//     tiktok: "ตัวดาวน์โหลดวิดีโอ TikTok",
//     instagram: "ตัวดาวน์โหลดวิดีโอ Instagram",
//     youtube: "ตัวดาวน์โหลดวิดีโอ YouTube",
//     youtubeMp3: "ตัวแปลง YouTube เป็น MP3",
//     facebook: "ตัวดาวน์โหลดวิดีโอ Facebook",
//     twitter: "ตัวดาวน์โหลดวิดีโอ Twitter",
//   },
//   tr: {
//     tiktok: "TikTok Video İndirici",
//     instagram: "Instagram Video İndirici",
//     youtube: "YouTube Video İndirici",
//     youtubeMp3: "YouTube MP3 Dönüştürücü",
//     facebook: "Facebook Video İndirici",
//     twitter: "Twitter Video İndirici",
//   },
//   zh: {
//     tiktok: "抖音视频下载工具",
//     instagram: "Instagram 视频下载工具",
//     youtube: "油管视频下载工具",
//     youtubeMp3: "YouTube 转 MP3 工具",
//     facebook: "脸书视频下载工具",
//     twitter: "推特视频下载工具",
//   },
//   "zh-TW": {
//     tiktok: "抖音影片下載工具",
//     instagram: "Instagram 影片下載工具",
//     youtube: "YouTube 影片下載工具",
//     youtubeMp3: "YouTube 轉 MP3 工具",
//     facebook: "臉書影片下載工具",
//     twitter: "推特影片下載工具",
//   },
//   bn: {
//     tiktok: "টিকটক ভিডিও ডাউনলোডার",
//     instagram: "ইনস্টাগ্রাম ভিডিও ডাউনলোডার",
//     youtube: "ইউটিউব ভিডিও ডাউনলোডার",
//     youtubeMp3: "ইউটিউব MP3 কনভার্টার",
//     facebook: "ফেসবুক ভিডিও ডাউনলোডার",
//     twitter: "টুইটার ভিডিও ডাউনলোডার",
//   },
//   ar: {
//     tiktok: "أداة تنزيل فيديو تيك توك",
//     instagram: "أداة تنزيل فيديو إنستغرام",
//     youtube: "أداة تنزيل فيديو يوتيوب",
//     youtubeMp3: "محول يوتيوب إلى MP3",
//     facebook: "أداة تنزيل فيديو فيسبوك",
//     twitter: "أداة تنزيل فيديو تويتر",
//   },
// };







export const platformNames: Record<
  string,
  {
    heading: string;
    tiktok: string;
    instagram: string;
    youtube: string;
    youtubeMp3: string;
    facebook: string;
    twitter: string;
  }
> = {
  en: {
    heading: "Download Videos from Your Favorite Platforms",
    tiktok: "TikTok Video Download Tool",
    instagram: "Instagram Video Download Tool",
    youtube: "YouTube Video Download Tool",
    youtubeMp3: "YouTube to MP3 Converter Tool",
    facebook: "Facebook Video Download Tool",
    twitter: "Twitter Video Download Tool",
  },
  de: {
    heading: "Videos von Ihren Lieblingsplattformen herunterladen",
    tiktok: "TikTok Video Downloaden Tool",
    instagram: "Instagram Video Downloaden Tool",
    youtube: "YouTube Video Downloaden Tool",
    youtubeMp3: "YouTube zu MP3 Konverter",
    facebook: "Facebook Video Downloaden Tool",
    twitter: "Twitter Video Downloaden Tool",
  },
  es: {
    heading: "Descarga videos de tus plataformas favoritas",
    tiktok: "Descargador de videos de TikTok",
    instagram: "Descargador de videos de Instagram",
    youtube: "Descargador de videos de YouTube",
    youtubeMp3: "Convertidor de YouTube a MP3",
    facebook: "Descargador de videos de Facebook",
    twitter: "Descargador de videos de Twitter",
  },
  fr: {
    heading: "Téléchargez des vidéos depuis vos plateformes préférées",
    tiktok: "Téléchargeur de vidéos TikTok",
    instagram: "Téléchargeur de vidéos Instagram",
    youtube: "Téléchargeur de vidéos YouTube",
    youtubeMp3: "Convertisseur YouTube en MP3",
    facebook: "Téléchargeur de vidéos Facebook",
    twitter: "Téléchargeur de vidéos Twitter",
  },
  hi: {
    heading: "अपनी पसंदीदा प्लेटफ़ॉर्म से वीडियो डाउनलोड करें",
    tiktok: "टिकटॉक वीडियो डाउनलोड टूल",
    instagram: "इंस्टाग्राम वीडियो डाउनलोड टूल",
    youtube: "यूट्यूब वीडियो डाउनलोड टूल",
    youtubeMp3: "यूट्यूब से MP3 कनवर्टर टूल",
    facebook: "फेसबुक वीडियो डाउनलोड टूल",
    twitter: "ट्विटर वीडियो डाउनलोड टूल",
  },
  id: {
    heading: "Unduh Video dari Platform Favorit Anda",
    tiktok: "Pengunduh Video TikTok",
    instagram: "Pengunduh Video Instagram",
    youtube: "Pengunduh Video YouTube",
    youtubeMp3: "Konverter YouTube ke MP3",
    facebook: "Pengunduh Video Facebook",
    twitter: "Pengunduh Video Twitter",
  },
  it: {
    heading: "Scarica video dalle tue piattaforme preferite",
    tiktok: "Scarica video TikTok",
    instagram: "Scarica video Instagram",
    youtube: "Scarica video YouTube",
    youtubeMp3: "Convertitore YouTube in MP3",
    facebook: "Scarica video Facebook",
    twitter: "Scarica video Twitter",
  },
  ja: {
    heading: "お気に入りのプラットフォームから動画をダウンロード",
    tiktok: "ティックトック動画ダウンローダー",
    instagram: "インスタグラム動画ダウンローダー",
    youtube: "ユーチューブ動画ダウンローダー",
    youtubeMp3: "ユーチューブMP3変換ツール",
    facebook: "フェイスブック動画ダウンローダー",
    twitter: "ツイッター動画ダウンローダー",
  },
  ko: {
    heading: "좋아하는 플랫폼에서 동영상 다운로드",
    tiktok: "틱톡 동영상 다운로드 도구",
    instagram: "인스타그램 동영상 다운로드 도구",
    youtube: "유튜브 동영상 다운로드 도구",
    youtubeMp3: "유튜브 MP3 변환 도구",
    facebook: "페이스북 동영상 다운로드 도구",
    twitter: "트위터 동영상 다운로드 도구",
  },
  ms: {
    heading: "Muat turun video dari platform kegemaran anda",
    tiktok: "Muat Turun Video TikTok",
    instagram: "Muat Turun Video Instagram",
    youtube: "Muat Turun Video YouTube",
    youtubeMp3: "Penukar YouTube ke MP3",
    facebook: "Muat Turun Video Facebook",
    twitter: "Muat Turun Video Twitter",
  },
  my: {
    heading: "သင်နှစ်သက်သော ပလက်ဖောင်းများမှ ဗီဒီယိုများ ဒေါင်းလုပ်လုပ်ရန်",
    tiktok: "TikTok ဗီဒီယိုဒေါင်းလုပ်ကိရိယာ",
    instagram: "Instagram ဗီဒီယိုဒေါင်းလုပ်ကိရိယာ",
    youtube: "YouTube ဗီဒီယိုဒေါင်းလုပ်ကိရိယာ",
    youtubeMp3: "YouTube ကို MP3 သို့ပြောင်းသည့်ကိရိယာ",
    facebook: "Facebook ဗီဒီယိုဒေါင်းလုပ်ကိရိယာ",
    twitter: "Twitter ဗီဒီယိုဒေါင်းလုပ်ကိရိယာ",
  },
  fil: {
    heading: "I-download ang mga video mula sa iyong paboritong mga platform",
    tiktok: "Downloader ng TikTok Video",
    instagram: "Downloader ng Instagram Video",
    youtube: "Downloader ng YouTube Video",
    youtubeMp3: "YouTube sa MP3 Converter Tool",
    facebook: "Downloader ng Facebook Video",
    twitter: "Downloader ng Twitter Video",
  },
  pt: {
    heading: "Baixe vídeos de suas plataformas favoritas",
    tiktok: "Baixador de vídeos TikTok",
    instagram: "Baixador de vídeos Instagram",
    youtube: "Baixador de vídeos YouTube",
    youtubeMp3: "Conversor de YouTube para MP3",
    facebook: "Baixador de vídeos Facebook",
    twitter: "Baixador de vídeos Twitter",
  },
  ru: {
    heading: "Скачивайте видео с ваших любимых платформ",
    tiktok: "Загрузчик видео TikTok",
    instagram: "Загрузчик видео Instagram",
    youtube: "Загрузчик видео YouTube",
    youtubeMp3: "Конвертер YouTube в MP3",
    facebook: "Загрузчик видео Facebook",
    twitter: "Загрузчик видео Twitter",
  },
  th: {
    heading: "ดาวน์โหลดวิดีโอจากแพลตฟอร์มที่คุณชื่นชอบ",
    tiktok: "ตัวดาวน์โหลดวิดีโอ TikTok",
    instagram: "ตัวดาวน์โหลดวิดีโอ Instagram",
    youtube: "ตัวดาวน์โหลดวิดีโอ YouTube",
    youtubeMp3: "ตัวแปลง YouTube เป็น MP3",
    facebook: "ตัวดาวน์โหลดวิดีโอ Facebook",
    twitter: "ตัวดาวน์โหลดวิดีโอ Twitter",
  },
  tr: {
    heading: "Favori platformlarınızdan videoları indirin",
    tiktok: "TikTok Video İndirici",
    instagram: "Instagram Video İndirici",
    youtube: "YouTube Video İndirici",
    youtubeMp3: "YouTube MP3 Dönüştürücü",
    facebook: "Facebook Video İndirici",
    twitter: "Twitter Video İndirici",
  },
  zh: {
    heading: "从您喜爱的平台注册视频",
    tiktok: "抖音视频下载工具",
    instagram: "Instagram 视频下载工具",
    youtube: "油管视频下载工具",
    youtubeMp3: "YouTube 转 MP3 工具",
    facebook: "脸书视频下载工具",
    twitter: "推特视频下载工具",
  },
  "zh-TW": {
    heading: "從您喜愛的平台下載影片",
    tiktok: "抖音影片下載工具",
    instagram: "Instagram 影片下載工具",
    youtube: "YouTube 影片下載工具",
    youtubeMp3: "YouTube 轉 MP3 工具",
    facebook: "臉書影片下載工具",
    twitter: "推特影片下載工具",
  },
  bn: {
    heading: "আপনার প্রিয় প্ল্যাটফর্ম থেকে ভিডিও ডাউনলোড করুন",
    tiktok: "টিকটক ভিডিও ডাউনলোডার",
    instagram: "ইনস্টাগ্রাম ভিডিও ডাউনলোডার",
    youtube: "ইউটিউব ভিডিও ডাউনলোডার",
    youtubeMp3: "ইউটিউব MP3 কনভার্টার",
    facebook: "ফেসবুক ভিডিও ডাউনলোডার",
    twitter: "টুইটার ভিডিও ডাউনলোডার",
  },
  ar: {
    heading: "قم بتنزيل مقاطع الفيديو من منصاتك المفضلة",
    tiktok: "أداة تنزيل فيديو تيك توك",
    instagram: "أداة تنزيل فيديو إنستغرام",
    youtube: "أداة تنزيل فيديو يوتيوب",
    youtubeMp3: "محول يوتيوب إلى MP3",
    facebook: "أداة تنزيل فيديو فيسبوك",
    twitter: "أداة تنزيل فيديو تويتر",
  },
};
